package com.rmbih.model;

public class RmbihUserT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.LOGIN_NAME
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.LOGIN_PASSWORD
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.TOKEN
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.ROLE
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.MARKER_FLAG
     *
     * @mbggenerated
     */
    private String markerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.INPUT_NAME
     *
     * @mbggenerated
     */
    private String inputName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.INPUT_DATE
     *
     * @mbggenerated
     */
    private String inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.UPDATE_NAME
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.UPDATE_DATE
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmbih_user_t.DELSIGN
     *
     * @mbggenerated
     */
    private Short delsign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.ID
     *
     * @return the value of rmbih_user_t.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.ID
     *
     * @param id the value for rmbih_user_t.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.LOGIN_NAME
     *
     * @return the value of rmbih_user_t.LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.LOGIN_NAME
     *
     * @param loginName the value for rmbih_user_t.LOGIN_NAME
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.LOGIN_PASSWORD
     *
     * @return the value of rmbih_user_t.LOGIN_PASSWORD
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.LOGIN_PASSWORD
     *
     * @param loginPassword the value for rmbih_user_t.LOGIN_PASSWORD
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.USER_NAME
     *
     * @return the value of rmbih_user_t.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.USER_NAME
     *
     * @param userName the value for rmbih_user_t.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.TOKEN
     *
     * @return the value of rmbih_user_t.TOKEN
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.TOKEN
     *
     * @param token the value for rmbih_user_t.TOKEN
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.ROLE
     *
     * @return the value of rmbih_user_t.ROLE
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.ROLE
     *
     * @param role the value for rmbih_user_t.ROLE
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.STATUS
     *
     * @return the value of rmbih_user_t.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.STATUS
     *
     * @param status the value for rmbih_user_t.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.MARKER_FLAG
     *
     * @return the value of rmbih_user_t.MARKER_FLAG
     *
     * @mbggenerated
     */
    public String getMarkerFlag() {
        return markerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.MARKER_FLAG
     *
     * @param markerFlag the value for rmbih_user_t.MARKER_FLAG
     *
     * @mbggenerated
     */
    public void setMarkerFlag(String markerFlag) {
        this.markerFlag = markerFlag == null ? null : markerFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.INPUT_NAME
     *
     * @return the value of rmbih_user_t.INPUT_NAME
     *
     * @mbggenerated
     */
    public String getInputName() {
        return inputName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.INPUT_NAME
     *
     * @param inputName the value for rmbih_user_t.INPUT_NAME
     *
     * @mbggenerated
     */
    public void setInputName(String inputName) {
        this.inputName = inputName == null ? null : inputName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.INPUT_DATE
     *
     * @return the value of rmbih_user_t.INPUT_DATE
     *
     * @mbggenerated
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.INPUT_DATE
     *
     * @param inputDate the value for rmbih_user_t.INPUT_DATE
     *
     * @mbggenerated
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.UPDATE_NAME
     *
     * @return the value of rmbih_user_t.UPDATE_NAME
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.UPDATE_NAME
     *
     * @param updateName the value for rmbih_user_t.UPDATE_NAME
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.UPDATE_DATE
     *
     * @return the value of rmbih_user_t.UPDATE_DATE
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.UPDATE_DATE
     *
     * @param updateDate the value for rmbih_user_t.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmbih_user_t.DELSIGN
     *
     * @return the value of rmbih_user_t.DELSIGN
     *
     * @mbggenerated
     */
    public Short getDelsign() {
        return delsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmbih_user_t.DELSIGN
     *
     * @param delsign the value for rmbih_user_t.DELSIGN
     *
     * @mbggenerated
     */
    public void setDelsign(Short delsign) {
        this.delsign = delsign;
    }
}