package com.rmbih.dao;

import com.rmbih.model.RmbihPicT;
import com.rmbih.model.RmbihPicTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RmbihPicTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int countByExample(RmbihPicTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int deleteByExample(RmbihPicTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int insert(RmbihPicT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int insertSelective(RmbihPicT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    List<RmbihPicT> selectByExample(RmbihPicTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    RmbihPicT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RmbihPicT record, @Param("example") RmbihPicTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RmbihPicT record, @Param("example") RmbihPicTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RmbihPicT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmbih_pic_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RmbihPicT record);
}